### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by stbuehler** [nodakai/rust-static_assert_macro#3]
As far as I can tell this doesn't work (anymore), i.e. it doesn't detect failures.

The "negative" test case in the source is already broken on the type level (`expected bool, found integer`); but a check evaluating to `false` still compiles.

**Comment by stbuehler** [comment]
It seems the compiler ignores problems in unused type aliases; a real struct with the magic field type works for me.

**Comment by nodakai** [comment]
Thanks for reporting. I chose a function definition involving the same constant overflow which is a bit shorter than defining a struct. Wonder if there's a quick way to *expect* a compile failure in Travis...

I think `expected bool, found integer` was intentional in that the macro will not accept integral arguments unlike C's counterpart (`assert`). Clarified the intention by renaming the unit tests.

**Comment by stbuehler** [comment]
Thanks for the quick fix! (didn't test it yet though :) )

> [...] Wonder if there's a quick way to _expect_ a compile failure in Travis...

Hm. I'd assume the rust compiler does have such tests, but never bothered to look how they are implemented.

**Comment by nodakai** [comment]
@all-contributors please add @stbuehler for bug
